# 应用名称
spring:
  application:
    name: vast-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/
